export const TEAMS = [
  {
    id: "bmw",
    name: "BMW Team",
    theme: "precision street tuning",
    accentColor: "#4c8dff",
    vehicles: [
      {
        id: "bmw-m3-coupe",
        name: "M3-inspired Coupe",
        shortName: "M3 Coupe",
        className: "Sport Coupe",
        description: "Compact, balanced, and eager to rotate through tight corners.",
        bodyColor: 0x1f66d1,
        stripeColor: 0xf7f7f2,
        image: "./assets/vehicles/bmw-m3-coupe.svg",
        maxForwardSpeed: 56,
        acceleration: 38,
        lateralGrip: 8.4,
        handbrakeGrip: 2.35,
        turnRate: 2.9,
        airDrag: 0.013,
        engineProfile: { idleHz: 64, maxHz: 295, roughness: 5, gain: 1 },
        width: 4.15,
        length: 7.05,
        height: 0.72,
        cabinWidth: 3.1,
        cabinLength: 2.85,
        cabinHeight: 0.88,
        cabinOffsetZ: -0.62,
        spoilerWidth: 4.1,
      },
      {
        id: "bmw-m5-sedan",
        name: "M5-inspired Sedan",
        shortName: "M5 Sedan",
        className: "Performance Sedan",
        description: "Longer wheelbase, planted stance, and strong highway pull.",
        bodyColor: 0x2d343c,
        stripeColor: 0xb6d8ff,
        image: "./assets/vehicles/bmw-m5-sedan.svg",
        maxForwardSpeed: 59,
        acceleration: 34,
        lateralGrip: 7.25,
        handbrakeGrip: 2.15,
        turnRate: 2.35,
        airDrag: 0.011,
        engineProfile: { idleHz: 58, maxHz: 250, roughness: 4, gain: 1.08 },
        width: 4.35,
        length: 7.75,
        height: 0.78,
        cabinWidth: 3.25,
        cabinLength: 3.45,
        cabinHeight: 0.96,
        cabinOffsetZ: -0.45,
        spoilerWidth: 3.5,
      },
      {
        id: "bmw-m4-coupe",
        name: "M4-inspired Coupe",
        shortName: "M4 Coupe",
        className: "Widebody Coupe",
        description: "Lower, wider, and happier sliding under handbrake.",
        bodyColor: 0xdedede,
        stripeColor: 0x1f66d1,
        image: "./assets/vehicles/bmw-m4-coupe.svg",
        maxForwardSpeed: 58,
        acceleration: 39,
        lateralGrip: 7.8,
        handbrakeGrip: 2,
        turnRate: 2.7,
        airDrag: 0.012,
        engineProfile: { idleHz: 66, maxHz: 305, roughness: 6, gain: 1.02 },
        width: 4.45,
        length: 7.25,
        height: 0.68,
        cabinWidth: 3.15,
        cabinLength: 2.75,
        cabinHeight: 0.82,
        cabinOffsetZ: -0.78,
        spoilerWidth: 4.55,
      },
      {
        id: "bmw-m2-club",
        name: "M2-inspired Club Coupe",
        shortName: "M2 Club",
        className: "Light Coupe",
        description: "Short, nimble, and easy to place, but lower on top-end speed.",
        bodyColor: 0x5aa7ff,
        stripeColor: 0x11151c,
        image: "./assets/vehicles/bmw-m2-club.svg",
        maxForwardSpeed: 53,
        acceleration: 39,
        lateralGrip: 8.9,
        handbrakeGrip: 2.55,
        turnRate: 3.1,
        airDrag: 0.014,
        engineProfile: { idleHz: 68, maxHz: 320, roughness: 6, gain: 0.95 },
        width: 3.95,
        length: 6.65,
        height: 0.7,
        cabinWidth: 2.95,
        cabinLength: 2.65,
        cabinHeight: 0.86,
        cabinOffsetZ: -0.62,
        spoilerWidth: 3.8,
      },
      {
        id: "bmw-8-gt",
        name: "8-inspired Grand Tourer",
        shortName: "8 GT",
        className: "Grand Tourer",
        description: "Fast and stable on straights, heavier through tight bends.",
        bodyColor: 0x17345a,
        stripeColor: 0xd8b45f,
        image: "./assets/vehicles/bmw-8-gt.svg",
        maxForwardSpeed: 61,
        acceleration: 35,
        lateralGrip: 6.95,
        handbrakeGrip: 1.9,
        turnRate: 2.18,
        airDrag: 0.0105,
        engineProfile: { idleHz: 54, maxHz: 245, roughness: 3.5, gain: 1.12 },
        width: 4.55,
        length: 8.1,
        height: 0.72,
        cabinWidth: 3.18,
        cabinLength: 3.1,
        cabinHeight: 0.86,
        cabinOffsetZ: -0.7,
        spoilerWidth: 3.4,
      },
    ],
  },
  {
    id: "porsche",
    name: "Porsche Team",
    theme: "rear-engine arcade speed",
    accentColor: "#ff4c45",
    vehicles: [
      {
        id: "porsche-911-sports",
        name: "911-inspired Sports Car",
        shortName: "911 Sport",
        className: "Rear Sports Car",
        description: "Short, fast, and lively when the rear steps out.",
        bodyColor: 0xd82828,
        stripeColor: 0x141414,
        image: "./assets/vehicles/porsche-911-sports.svg",
        maxForwardSpeed: 57,
        acceleration: 40,
        lateralGrip: 7.55,
        handbrakeGrip: 2.05,
        turnRate: 2.78,
        airDrag: 0.0115,
        engineProfile: { idleHz: 72, maxHz: 330, roughness: 7, gain: 1.02 },
        width: 4.05,
        length: 6.75,
        height: 0.66,
        cabinWidth: 2.95,
        cabinLength: 2.35,
        cabinHeight: 0.82,
        cabinOffsetZ: -0.25,
        spoilerWidth: 3.85,
      },
      {
        id: "porsche-cayman-sports",
        name: "Cayman-inspired Sports Car",
        shortName: "Cayman",
        className: "Mid Sports Car",
        description: "Neutral handling with clean steering response.",
        bodyColor: 0xf2a51e,
        stripeColor: 0x1a1a1a,
        image: "./assets/vehicles/porsche-cayman-sports.svg",
        maxForwardSpeed: 54,
        acceleration: 38,
        lateralGrip: 8.85,
        handbrakeGrip: 2.5,
        turnRate: 3.05,
        airDrag: 0.013,
        engineProfile: { idleHz: 70, maxHz: 318, roughness: 6.5, gain: 0.97 },
        width: 4,
        length: 6.55,
        height: 0.64,
        cabinWidth: 2.85,
        cabinLength: 2.25,
        cabinHeight: 0.78,
        cabinOffsetZ: -0.55,
        spoilerWidth: 3.65,
      },
      {
        id: "porsche-carrera-gt-supercar",
        name: "Carrera GT-inspired Supercar",
        shortName: "GT Supercar",
        className: "Analog Supercar",
        description: "Low, dramatic, and built for big sweeping corners.",
        bodyColor: 0xc8c9c7,
        stripeColor: 0x831f23,
        image: "./assets/vehicles/porsche-carrera-gt-supercar.svg",
        maxForwardSpeed: 61,
        acceleration: 42,
        lateralGrip: 7.15,
        handbrakeGrip: 1.95,
        turnRate: 2.35,
        airDrag: 0.0105,
        engineProfile: { idleHz: 76, maxHz: 350, roughness: 8, gain: 1.1 },
        width: 4.55,
        length: 7.35,
        height: 0.58,
        cabinWidth: 2.95,
        cabinLength: 2.15,
        cabinHeight: 0.72,
        cabinOffsetZ: -0.85,
        spoilerWidth: 4.75,
      },
      {
        id: "porsche-boxster-roadster",
        name: "Boxster-inspired Roadster",
        shortName: "Roadster",
        className: "Light Roadster",
        description: "Very agile and forgiving, but gives up speed on long straights.",
        bodyColor: 0x3bb8d8,
        stripeColor: 0xf7f7f2,
        image: "./assets/vehicles/porsche-boxster-roadster.svg",
        maxForwardSpeed: 52,
        acceleration: 37,
        lateralGrip: 9.05,
        handbrakeGrip: 2.65,
        turnRate: 3.16,
        airDrag: 0.0145,
        engineProfile: { idleHz: 73, maxHz: 325, roughness: 6, gain: 0.94 },
        width: 3.9,
        length: 6.35,
        height: 0.62,
        cabinWidth: 2.7,
        cabinLength: 2.05,
        cabinHeight: 0.72,
        cabinOffsetZ: -0.44,
        spoilerWidth: 3.3,
      },
      {
        id: "porsche-918-hybrid",
        name: "918-inspired Hybrid Supercar",
        shortName: "918 Hybrid",
        className: "Hybrid Supercar",
        description: "Brutal acceleration and top speed, with heavier turn-in.",
        bodyColor: 0x0f1a22,
        stripeColor: 0x79e36c,
        image: "./assets/vehicles/porsche-918-hybrid.svg",
        maxForwardSpeed: 62,
        acceleration: 44,
        lateralGrip: 7.35,
        handbrakeGrip: 1.85,
        turnRate: 2.22,
        airDrag: 0.01,
        engineProfile: { idleHz: 60, maxHz: 300, roughness: 5.5, gain: 1.08 },
        width: 4.6,
        length: 7.45,
        height: 0.56,
        cabinWidth: 2.82,
        cabinLength: 2.05,
        cabinHeight: 0.68,
        cabinOffsetZ: -0.72,
        spoilerWidth: 4.95,
      },
    ],
  },
];

export function findVehicle(vehicleId) {
  for (const team of TEAMS) {
    const vehicle = team.vehicles.find((candidate) => candidate.id === vehicleId);

    if (vehicle) {
      return { team, vehicle };
    }
  }

  return { team: TEAMS[0], vehicle: TEAMS[0].vehicles[0] };
}
