export const TEAMS = [
  {
    id: "bmw",
    name: "BMW Team",
    theme: "precision street tuning",
    accentColor: "#4c8dff",
    vehicles: [
      {
        id: "bmw-m3-coupe",
        name: "M3-inspired Coupe",
        shortName: "M3 Coupe",
        className: "Sport Coupe",
        description: "Compact, balanced, and eager to rotate through tight corners.",
        bodyColor: 0x1f66d1,
        stripeColor: 0xf7f7f2,
        width: 4.15,
        length: 7.05,
        height: 0.72,
        cabinWidth: 3.1,
        cabinLength: 2.85,
        cabinHeight: 0.88,
        cabinOffsetZ: -0.62,
        spoilerWidth: 4.1,
      },
      {
        id: "bmw-m5-sedan",
        name: "M5-inspired Sedan",
        shortName: "M5 Sedan",
        className: "Performance Sedan",
        description: "Longer wheelbase, planted stance, and strong highway pull.",
        bodyColor: 0x2d343c,
        stripeColor: 0xb6d8ff,
        width: 4.35,
        length: 7.75,
        height: 0.78,
        cabinWidth: 3.25,
        cabinLength: 3.45,
        cabinHeight: 0.96,
        cabinOffsetZ: -0.45,
        spoilerWidth: 3.5,
      },
      {
        id: "bmw-m4-coupe",
        name: "M4-inspired Coupe",
        shortName: "M4 Coupe",
        className: "Widebody Coupe",
        description: "Lower, wider, and happier sliding under handbrake.",
        bodyColor: 0xdedede,
        stripeColor: 0x1f66d1,
        width: 4.45,
        length: 7.25,
        height: 0.68,
        cabinWidth: 3.15,
        cabinLength: 2.75,
        cabinHeight: 0.82,
        cabinOffsetZ: -0.78,
        spoilerWidth: 4.55,
      },
    ],
  },
  {
    id: "porsche",
    name: "Porsche Team",
    theme: "rear-engine arcade speed",
    accentColor: "#ff4c45",
    vehicles: [
      {
        id: "porsche-911-sports",
        name: "911-inspired Sports Car",
        shortName: "911 Sport",
        className: "Rear Sports Car",
        description: "Short, fast, and lively when the rear steps out.",
        bodyColor: 0xd82828,
        stripeColor: 0x141414,
        width: 4.05,
        length: 6.75,
        height: 0.66,
        cabinWidth: 2.95,
        cabinLength: 2.35,
        cabinHeight: 0.82,
        cabinOffsetZ: -0.25,
        spoilerWidth: 3.85,
      },
      {
        id: "porsche-cayman-sports",
        name: "Cayman-inspired Sports Car",
        shortName: "Cayman",
        className: "Mid Sports Car",
        description: "Neutral handling with clean steering response.",
        bodyColor: 0xf2a51e,
        stripeColor: 0x1a1a1a,
        width: 4,
        length: 6.55,
        height: 0.64,
        cabinWidth: 2.85,
        cabinLength: 2.25,
        cabinHeight: 0.78,
        cabinOffsetZ: -0.55,
        spoilerWidth: 3.65,
      },
      {
        id: "porsche-carrera-gt-supercar",
        name: "Carrera GT-inspired Supercar",
        shortName: "GT Supercar",
        className: "Analog Supercar",
        description: "Low, dramatic, and built for big sweeping corners.",
        bodyColor: 0xc8c9c7,
        stripeColor: 0x831f23,
        width: 4.55,
        length: 7.35,
        height: 0.58,
        cabinWidth: 2.95,
        cabinLength: 2.15,
        cabinHeight: 0.72,
        cabinOffsetZ: -0.85,
        spoilerWidth: 4.75,
      },
    ],
  },
];

export function findVehicle(vehicleId) {
  for (const team of TEAMS) {
    const vehicle = team.vehicles.find((candidate) => candidate.id === vehicleId);

    if (vehicle) {
      return { team, vehicle };
    }
  }

  return { team: TEAMS[0], vehicle: TEAMS[0].vehicles[0] };
}
